### ISSUE TITLE
Unable to get coverage

### ISSUE THREAD

**Issue by MohdAli98** [samuelcolvin/coverage-badge#2]
`Hi,` I have successfully uploaded the coverage file using smokeshow but I am not able to embed the coverage badge in my README due to the following error.

`502: Unexpected response from "https://api.github.com/repos/my_org/my_repo/commits?per_page=5" 404 body:
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/commits/commits#list-commits"}`
@samuelcolvin can you help me with what I am missing?
FYI, its a private repo.

**Comment by samuelcolvin** [comment]
ye, we use the public API to get the status commit status, so there's nothing we can do with private repos.
